### PR TITLE
add service_account credentials support

### PR DESCRIPTION
**Pull request by sehnem**
Added support for service account credentials, it is a simple change and should not impact anything else. Also solves #29.

### CODE REVIEW

**Comment by martindurant** [comment]
Thank you, that's great!

Could you please give a little description of how to use this feature, at least how you would go about getting the right form of token to use?

**Comment by sehnem** [comment]
The [service account](https://cloud.google.com/iam/docs/service-account-creds#key-types) credentials are created in GCP and give you a `json` file containing the needed keys.
The service account contains an email, something like `drive-account@bq-proj-360014.iam.gserviceaccount.com`, and everything that is shared with this email can be accesses with the service account credentials.

To use those credentials you just need to give the credentials as a dictionary.
```python
file = "gdrive_sa.json"
with open(file, 'r') as f:
    gd_creds = json.loads(f.read())

gdfs = gdrivefs.GoogleDriveFileSystem(token=token, root_file_id=root_file_id, creds=gd_creds)
```

It is useful for pipelines that do not want user interaction.

**Comment by martindurant** [comment]
It is time we had a proper prose documentation for this project, so we can include helpful descriptions like this.

For the time being, an abbreviated version could be put directly in the docstring where `creds` is described.

**Comment by sehnem** [comment]
Added a more detailed description to de docstrings.

**Comment by martindurant** [comment]
Perfect, thank.

**Pull request merged**
