### PR TITLE
get rid of versioneer

### PR DESCRIPTION
**Pull request by efiop**
We use gdrivefs for testing in dvc-gdrive and versionner started getting in the way, so I decided to contribute a PR here as well (we have our own test fork).

It does't work with 3.12 as is and is not necessary anyway, setuptools-scm is a hustle-free way to go these days.

Was forced to use pyproject, so migrated to it from setup.py/cfg along the way as well.

### CODE REVIEW

**Comment by efiop** [comment]
@martindurant I'm not sure if you still have the keys or how long it has been since the tests were operational, but if you could find a key for encrypted secrets used in https://github.com/fsspec/gdrivefs/blob/master/.travis.yml  and/or set up those secrets unencrypted in this repo's secrets, I'm happy to try enabling the tests. I think for now I'll just add some basic logic to make sure that this is at least installable.

**Comment by efiop** [comment]
Merged for now to enable gha CI (could've done it the other way around, but too late now :( )

**Comment by martindurant** [comment]
+1

**Comment by martindurant** [comment]
I don't think travis should b used at all; I don't think the tests here were ever run in CI, and they should not be sun against production Gdrive anyway. Unfortunately, I don't think there's any emulator out there, and so we would have to resort to vcrpy (ugh).

**Comment by efiop** [comment]
@martindurant Right, I didn't mean we would ressurect travis, but setup secrets here so that gha that I've set up would work.

We use production gdrive in our tests, haven't found a simpler way really. Though I didn't have to deal with vcrpy in the past, but I would have to guess that it is way more involved than just setting up some dummy google account. Though we also didn't contribute service account support (this is very unlike us, but it kinda got lost during our migration), which would help here with that, so it is at least not interactive. So maybe this could wait until https://github.com/efiop/gdrivefs/tree/service-account is contributed back. For now at least we test that the package is getting installed, which is at least something 😅

**Pull request merged**
